# Nombre de la Aplicacion
spring.application.name=historias-clinicas

# Configuracion de Conexion a SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:veterinaria.db?busy_timeout=60000

# Configuracion del pool de conexiones (Crucial para evitar bloqueos en SQLite)
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=30000

# Configuracion del dialecto
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true