# Nombre de la Aplicacion
spring.application.name=historias-clinicas

# Configuracion de Conexion a SQLite
spring.datasource.url=jdbc:sqlite:veterinaria.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# AHORA SÍ funcionará el dialecto de la comunidad
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

